-- TickUp Database Schema
-- Restore migration: creates Lists, Todos, and Users tables

-- ===================
-- Lists table
-- ===================
CREATE TABLE IF NOT EXISTS "public"."Lists" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- ===================
-- Todos table
-- ===================
CREATE TABLE IF NOT EXISTS "public"."Todos" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users ON DELETE CASCADE,
    list_id bigint REFERENCES "public"."Lists" ON DELETE CASCADE,
    name text NOT NULL,
    "desc" text,
    status text,
    priority text,
    type text,
    due_date timestamp with time zone,
    completed_date timestamp with time zone,
    "order" integer,
    color text DEFAULT '#87909e',
    notification_date_time timestamp with time zone,
    notification_sent boolean DEFAULT false,
    links jsonb DEFAULT '[]'::jsonb,
    subtasks jsonb DEFAULT '[]'::jsonb,
    attachments jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- ===================
-- Users table
-- ===================
CREATE TABLE IF NOT EXISTS "public"."Users" (
    id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    username text,
    push_subscriptions jsonb DEFAULT '[]'::jsonb,
    github_installation_id bigint,
    github_username text
);

-- ===================
-- Indexes
-- ===================
CREATE INDEX IF NOT EXISTS idx_todos_user_id ON "public"."Todos" (user_id);
CREATE INDEX IF NOT EXISTS idx_todos_list_id ON "public"."Todos" (list_id);
CREATE INDEX IF NOT EXISTS idx_todos_notification ON "public"."Todos" (notification_date_time) WHERE notification_sent IS NOT TRUE;
CREATE INDEX IF NOT EXISTS idx_lists_user_id ON "public"."Lists" (user_id);

-- ===================
-- Row Level Security
-- ===================

-- Enable RLS on all tables
ALTER TABLE "public"."Lists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Todos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;

-- Lists policies: users can only access their own lists
CREATE POLICY "Users can view own lists" ON "public"."Lists"
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own lists" ON "public"."Lists"
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own lists" ON "public"."Lists"
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own lists" ON "public"."Lists"
    FOR DELETE USING (auth.uid() = user_id);

-- Todos policies: users can only access their own todos
CREATE POLICY "Users can view own todos" ON "public"."Todos"
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own todos" ON "public"."Todos"
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own todos" ON "public"."Todos"
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own todos" ON "public"."Todos"
    FOR DELETE USING (auth.uid() = user_id);

-- Users policies: users can only access their own record
CREATE POLICY "Users can view own profile" ON "public"."Users"
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can create own profile" ON "public"."Users"
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON "public"."Users"
    FOR UPDATE USING (auth.uid() = id);

-- ===================
-- Auto-set user_id on insert via trigger
-- ===================

-- Function to auto-set user_id from auth context
CREATE OR REPLACE FUNCTION public.set_user_id()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.user_id IS NULL THEN
        NEW.user_id := auth.uid();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Apply trigger to Lists
CREATE TRIGGER set_lists_user_id
    BEFORE INSERT ON "public"."Lists"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_user_id();

-- Apply trigger to Todos
CREATE TRIGGER set_todos_user_id
    BEFORE INSERT ON "public"."Todos"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_user_id();
