name: Build Nuxt Project

on:
  push:
    branches:
      - e2e-testing

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      NUXT_NEXTAUTH_SECRET: ${{ secrets.NUXT_NEXTAUTH_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn dev