name: Playwright Tests (Dev Server)
on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      run: |
        # Set environment variables for installation
        export NODE_OPTIONS="--max-old-space-size=4096 --no-warnings"
        
        # Install dependencies
        pnpm install --no-frozen-lockfile --ignore-scripts
      
    - name: Cache Playwright browsers
      id: playwright-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ms-playwright
          node_modules/playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
          
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      
    - name: Create Playwright auth state file
      env:
        PLAYWRIGHT_AUTH_STATE_B64: ${{ secrets.PLAYWRIGHT_USER }}
      run: |
        echo "Creating storageState.json from secret..."
        echo "$PLAYWRIGHT_AUTH_STATE_B64" | base64 --decode > user.json
        echo "user.json created successfully."
        
    - name: Run Playwright tests
      run: pnpm exec playwright test
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NUXT_NEXTAUTH_SECRET: ${{ secrets.NUXT_NEXTAUTH_SECRET || 'test-secret-key-for-ci' }}
        NODE_ENV: test
        NODE_OPTIONS: "--max-old-space-size=4096 --no-warnings"
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30