name: Release with Changelog

on:
  push:
    tags: [ v*.*.* ]  # Triggers on pushing tags starting with "v"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout code

      - uses: gr2m/release-with-changelog@v1  # Use the release-with-changelog action
        with:
          tag_name: ${{ github.ref }}  # Set tag name from pushed ref
          file_content_type: markdown  # Release body format (optional)
